version: '3.4'

services:
  twt.api:
    image: ${DOCKER_REGISTRY-}twtapi
    build:
      context: .
      dockerfile: src/TWT.API/Dockerfile
    restart: always
  db:
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
