// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TWT.Data;

#nullable disable

namespace TWT.Data.Migrations
{
    [DbContext(typeof(CarStoreDbContext))]
    [Migration("20230115123755_addCarSeed")]
    partial class addCarSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TWT.Data.Models.Car", b =>
                {
                    b.Property<string>("LincensePlate")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("LincensePlate");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OwnerName");

                    b.Property<int>("Power")
                        .HasColumnType("int")
                        .HasColumnName("Power");

                    b.HasKey("LincensePlate");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            LincensePlate = "ABC-123",
                            OwnerName = "Erős Pista",
                            Power = 100
                        },
                        new
                        {
                            LincensePlate = "KIS-111",
                            OwnerName = "Kis Jani",
                            Power = 60
                        },
                        new
                        {
                            LincensePlate = "BIG-999",
                            OwnerName = "Nagy Karcsi",
                            Power = 300
                        },
                        new
                        {
                            LincensePlate = "BZS-150",
                            OwnerName = "Bali Zsolt",
                            Power = 155
                        },
                        new
                        {
                            LincensePlate = "BZS-300",
                            OwnerName = "Bali Zsolt",
                            Power = 300
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
